name: wts

services:

  rdbms:
    image: ${RDBMS_IMAGE}
    restart: unless-stopped
    shm_size: 128mb
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: ${ROOT_DB_NAME}
      POSTGRES_USER: ${ROOT_DB_USER}
      POSTGRES_PASSWORD: ${ROOT_DB_PASS}
      IAM_DB_NAME: ${IAM_DB_NAME}
      IAM_DB_USER: ${IAM_DB_USER}
      IAM_DB_PASS: ${IAM_DB_PASS}
      SESSIONS_DB_NAME: ${SESSIONS_DB_NAME}
      SESSIONS_DB_USER: ${SESSIONS_DB_USER}
      SESSIONS_DB_PASS: ${SESSIONS_DB_PASS}
      BACKEND_DB_NAME: ${BACKEND_DB_NAME}
      BACKEND_DB_USER: ${BACKEND_DB_USER}
      BACKEND_DB_PASS: ${BACKEND_DB_PASS}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - rdbms_vol
    networks:
      - rdbms_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${ROOT_DB_USER} -d $${ROOT_DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  iam:
    image: ${IAM_IMAGE}
    restart: unless-stopped
    command: start --optimized
    environment:
      TZ: Europe/Moscow
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: ${IAM_DB_NAME}
      KC_DB_USERNAME: ${IAM_DB_USER}
      KC_DB_PASSWORD: ${IAM_DB_PASS}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: true
      KC_CACHE: local
    ports:
      - "127.0.0.1:8085:8080"
    networks:
      - rdbms_net
      - iam_net
    healthcheck:
      test: ["CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready | echo $?"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      rdbms:
        condition: service_healthy

  gateway:
    image: ${GATEWAY_IMAGE}
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      SESSIONS_DB_NAME: ${SESSIONS_DB_NAME}
      SESSIONS_DB_USER: ${SESSIONS_DB_USER}
      SESSIONS_DB_PASS: ${SESSIONS_DB_PASS}
      GATEWAY_CLIENT_ID: ${GATEWAY_CLIENT_ID}
      GATEWAY_CLIENT_SECRET: ${GATEWAY_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      IAM_ISSUER_URI: ${IAM_ISSUER_URI}
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - rdbms_net
      - iam_net
      - tasks-service_net
    extra_hosts:
      - "auth.dipdeepcode.ru:212.109.223.138"
    depends_on:
      rdbms:
        condition: service_healthy
      iam:
        condition: service_healthy

  tasks-service:
    image: ${TASKS_SERVICE_IMAGE}
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      TASKS_SERVICE_DB_NAME: ${TASKS_SERVICE_DB_NAME}
      TASKS_SERVICE_DB_USER: ${TASKS_SERVICE_DB_USER}
      TASKS_SERVICE_DB_PASS: ${TASKS_SERVICE_DB_PASS}
      IAM_ISSUER_URI: ${IAM_ISSUER_URI}
    networks:
      - rdbms_net
      - iam_net
      - tasks-service_net
    extra_hosts:
      - "auth.dipdeepcode.ru:host-gateway"
    depends_on:
      rdbms:
        condition: service_healthy

volumes:
  rdbms_vol:
    name: rdbms_vol

networks:
  rdbms_net:
    name: rdbms_net
    driver: bridge
  iam_net:
    name: iam_net
    driver: bridge
  tasks-service_net:
    name: tasks-service_net
    driver: bridge
