version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: dipdeepcode/wts-postgres:17.4-alpine
    container_name: wts_postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      IAM_DB_USER: ${IAM_DB_USER}
      IAM_DB_PASS: ${IAM_DB_PASS}
      IAM_DB_NAME: ${IAM_DB_NAME}
      SESSIONS_DB_USER: ${SESSIONS_DB_USER}
      SESSIONS_DB_PASS: ${SESSIONS_DB_PASS}
      SESSIONS_DB_NAME: ${SESSIONS_DB_NAME}
      BACKEND_DB_USER: ${BACKEND_DB_USER}
      BACKEND_DB_PASS: ${BACKEND_DB_PASS}
      BACKEND_DB_NAME: ${BACKEND_DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  iam:
    build:
      context: ./iam
      dockerfile: Dockerfile
    image: dipdeepcode/wts-keycloak:26.7.0
    container_name: wts_keycloak
    restart: unless-stopped
    command: start --optimized
    environment:
      TZ: Europe/Moscow
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/${IAM_DB_NAME}
      KC_DB_USERNAME: ${IAM_DB_USER}
      KC_DB_PASSWORD: ${IAM_DB_PASS}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HTTP_ENABLED: true
      KC_CACHE: local
    ports:
      - "127.0.0.1:8085:8080"
    networks:
      - db_net
      - iam_net
    depends_on:
      database:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: dipdeepcode/wts-gateway:latest
    container_name: wts_gateway
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      SESSIONS_DB_NAME: ${SESSIONS_DB_NAME}
      SESSIONS_DB_USER: ${SESSIONS_DB_USER}
      SESSIONS_DB_PASS: ${SESSIONS_DB_PASS}
      GATEWAY_CLIENT_SECRET: ${GATEWAY_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_REALM_NAME: ${KC_REALM_NAME}
      GATEWAY_CLIENT_ID: ${GATEWAY_CLIENT_ID}
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - db_net
      - iam_net
    extra_hosts:
      - "auth.dipdeepcode.ru:212.109.223.138"
    depends_on:
      database:
        condition: service_healthy
      iam:
        condition: service_started

volumes:
  db_vol:
    name: db_vol

networks:
  db_net:
    name: db_net
  iam_net:
    name: iam_net