name: wts

services:

  database:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    shm_size: 128mb
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      IAM_DB_USER: ${IAM_DB_USER}
      IAM_DB_PASS: ${IAM_DB_PASS}
      IAM_DB_NAME: ${IAM_DB_NAME}
      SESSIONS_DB_USER: ${SESSIONS_DB_USER}
      SESSIONS_DB_PASS: ${SESSIONS_DB_PASS}
      SESSIONS_DB_NAME: ${SESSIONS_DB_NAME}
      BACKEND_DB_USER: ${BACKEND_DB_USER}
      BACKEND_DB_PASS: ${BACKEND_DB_PASS}
      BACKEND_DB_NAME: ${BACKEND_DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  iam:
    image: ${KEYCLOAK_IMAGE}
    restart: unless-stopped
    command: start --optimized
    environment:
      TZ: Europe/Moscow
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/${IAM_DB_NAME}
      KC_DB_USERNAME: ${IAM_DB_USER}
      KC_DB_PASSWORD: ${IAM_DB_PASS}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: true
      KC_CACHE: local
    ports:
      - "127.0.0.1:8085:8080"
    networks:
      - db_net
      - iam_net
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_vol:
    name: db_vol

networks:
  db_net:
    name: db_net
    external: true
  iam_net:
    name: iam_net
    external: true
