server:
  port: 8080
  ssl:
    enabled: false
  forward-headers-strategy: native

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${IAM_ISSUER_URI}
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://rdbms:5432/${SESSIONS_DB_NAME}
    username: ${SESSIONS_DB_USER}
    password: ${SESSIONS_DB_PASS}
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: tasks-service
              uri: http://tasks-service:8080/
              predicates:
                - Path=/api, /api/**
              filters:
                - TokenRelay=
                - RemoveRequestHeader=Cookie

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${IAM_ISSUER_URI}
            aud: ${GATEWAY_CLIENT_ID}
        client:
          # Внешний адрес вашего фронтенда Angular
          client-uri: ${FRONTEND_URL}
          post-login-allowed-uri-patterns:
            - ${FRONTEND_URL}/workspaces.*
            - ${FRONTEND_URL}/?
          post-logout-allowed-uri-patterns:
            - ${FRONTEND_URL}/?
          security-matchers:
            - /login/**
            - /oauth2/**
            - /logout/**
            - /api/**
          permit-all:
            - /login/**
            - /oauth2/**
            - /login-options
            - /api/me
          # Защита от CSRF. Библиотека создаст куку XSRF-TOKEN, которую Angular прочитает автоматически
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            # При логауте шлюз корректно оповестит Keycloak (302 редирект)
            rp-initiated-logout: ACCEPTED
            # Для API эндпоинтов шлюз вернет 401 вместо 302 редиректа на форму ввода пароля.
            # Это заставит Angular перехватить 401 ошибку и самостоятельно сделать редирект
            # браузера на эндпоинт инициализации: /oauth2/authorization/keycloak
            authentication-entry-point: UNAUTHORIZED
          pkce-forced: true
