server:
  port: 8080
  ssl:
    enabled: false

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://iam:8080/realms/wts
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: gateway
            client-secret: ${GATEWAY_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://database:5432/${SESSIONS_DB_NAME}
    username: ${SESSIONS_DB_USER}
    password: ${SESSIONS_DB_PASS}
    driver-class-name: org.postgresql.Driver
