#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
  CREATE USER $IAM_DB_USER WITH PASSWORD '$IAM_DB_PASS';
  CREATE DATABASE $IAM_DB_NAME WITH OWNER $IAM_DB_USER;
  CREATE USER $SESSIONS_DB_USER WITH PASSWORD '$SESSIONS_DB_PASS';
  CREATE DATABASE $SESSIONS_DB_NAME WITH OWNER $SESSIONS_DB_USER;
  CREATE USER $BACKEND_DB_USER WITH PASSWORD '$BACKEND_DB_PASS';
  CREATE DATABASE $BACKEND_DB_NAME WITH OWNER $BACKEND_DB_USER;
EOSQL