server {
	server_name auth.dipdeepcode.ru www.auth.dipdeepcode.ru;
	charset off;
	index index.php index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/auth.dipdeepcode.ru/*.conf;
	access_log /var/www/httpd-logs/auth.dipdeepcode.ru.access.log;
	error_log /var/www/httpd-logs/auth.dipdeepcode.ru.error.log notice;
	ssi on;
	return 301 https://$host:443$request_uri;
	set $root_path /var/www/dipdeepcode/data/www/auth.dipdeepcode.ru;
	root $root_path;
	listen 212.109.223.138:80;
	gzip on;
	gzip_comp_level 5;
	gzip_disable "msie6";
	gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;
	location / {
		location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf|webp|woff|woff2)$ {
			expires 24h;
		}
	}
}
server {
	server_name auth.dipdeepcode.ru www.auth.dipdeepcode.ru;
	ssl_certificate "/var/www/httpd-cert/dipdeepcode/dipdeepcode.ru_le1.crtca";
	ssl_certificate_key "/var/www/httpd-cert/dipdeepcode/dipdeepcode.ru_le1.key";
	ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	ssl_dhparam /etc/ssl/certs/dhparam4096.pem;
	charset off;
	index index.php index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/auth.dipdeepcode.ru/*.conf;
	access_log /var/www/httpd-logs/auth.dipdeepcode.ru.access.log;
	error_log /var/www/httpd-logs/auth.dipdeepcode.ru.error.log notice;
	ssi on;
	if ($host = www.auth.dipdeepcode.ru) {
		return 301 https://auth.dipdeepcode.ru$request_uri;
	}
	set $root_path /var/www/dipdeepcode/data/www/auth.dipdeepcode.ru;
	root $root_path;
	listen 212.109.223.138:443 ssl;
	gzip on;
	gzip_comp_level 5;
	gzip_disable "msie6";
	gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;
	location / {
		location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf|webp|woff|woff2)$ {
			expires 24h;
		}
	}
}