name: Create environment file

on:
  workflow_call:
permissions: {}

jobs:
  create_env:
    name: create env file
    environment: production
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Export data to env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{ vars.SERVER_PROJECT_PATH }}"
            set_env() {
              local key=$1
              local value=$2
              local file=${3:-.env}
              
              touch "$file" # Создает файл, если его нет
              
              if grep -q "^${key}=" "$file"; then
              sed -i "s/^${key}=.*/${key}=${value}/" "$file"
              else
              echo "${key}=${value}" >> "$file"
              fi
            }
            set_env RDBMS_IMAGE           ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.RDBMS_IMAGE_NAME }}
            set_env IAM_IMAGE             ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IAM_IMAGE_NAME }}
            set_env GATEWAY_IMAGE         ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.GATEWAY_IMAGE_NAME }}
            set_env TASKS_SERVICE_IMAGE   ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TASKS_SERVICE_IMAGE_NAME }}
            set_env GATEWAY_CLIENT_ID     ${{ secrets.GATEWAY_CLIENT_ID }}
            set_env GATEWAY_CLIENT_SECRET ${{ secrets.GATEWAY_CLIENT_SECRET }}
            set_env ROOT_DB_NAME          ${{ vars.ROOT_DB_NAME }}
            set_env ROOT_DB_USER          ${{ secrets.ROOT_DB_USER }}
            set_env ROOT_DB_PASS          ${{ secrets.ROOT_DB_PASS }}
            set_env IAM_DB_NAME           ${{ vars.IAM_DB_NAME }}
            set_env IAM_DB_USER           ${{ secrets.IAM_DB_USER }}
            set_env IAM_DB_PASS           ${{ secrets.IAM_DB_PASS }}
            set_env SESSIONS_DB_NAME      ${{ vars.SESSIONS_DB_NAME }}
            set_env SESSIONS_DB_USER      ${{ secrets.SESSIONS_DB_USER }}
            set_env SESSIONS_DB_PASS      ${{ secrets.SESSIONS_DB_PASS }}
            set_env TASKS_SERVICE_DB_NAME ${{ vars.TASKS_SERVICE_DB_NAME }}
            set_env TASKS_SERVICE_DB_USER ${{ secrets.TASKS_SERVICE_DB_USER }}
            set_env TASKS_SERVICE_DB_PASS ${{ secrets.TASKS_SERVICE_DB_PASS }}
            set_env KEYCLOAK_ADMIN_USER   ${{ secrets.KEYCLOAK_ADMIN_USER }}
            set_env KEYCLOAK_ADMIN_PASS   ${{ secrets.KEYCLOAK_ADMIN_PASS }}
            set_env KC_HOSTNAME           ${{ vars.KC_HOSTNAME }}
            set_env FRONTEND_URL          ${{ vars.FRONTEND_URL }}
            set_env IAM_ISSUER_URI        ${{ vars.KC_HOSTNAME }}/realms/${{ vars.KC_REALM_NAME }}



