name: create environment file

on:
  workflow_dispatch:
permissions: {}

jobs:
  create_env:
    name: create env file
    environment: production
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@7
      - name: Create env file
        uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{ vars.SERVER_PROJECT_PATH }}"
            set_env() {
              local key=$1
              local value=$2
              local file=${3:-.env}
              
              touch "$file" # Создает файл, если его нет
              
              if grep -q "^${key}=" "$file"; then
              sed -i "s/^${key}=.*/${key}=${value}/" "$file"
              else
              echo "${key}=${value}" >> "$file"
              fi
            }
            set_env API_KEY 12345



