name: Deploy Gateway

on:
  push:
    branches:
      - master
    paths:
      - 'gateway/**'
      - '.github/workflows/deploy-gateway.yml'
  workflow_run:
    workflows: ["Deploy Infrastructure (Postgres, Keycloak)"]
    types:
      - completed
permissions: {}
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/wts_gateway:latest

jobs:
  deploy-gateway:
    name: Deploy gateway
    environment: production
    permissions:
      contents: read
    runs-on: ubuntu-22.04

    # Если запуск произошел через workflow_run, проверяем, что предыдущий шаг завершился именно УСПЕШНО
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy docker-compose.yml to VDS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "${{ vars.SERVER_INFRA_PATH }}"

      - name: Deploy to VDS via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GATEWAY_CLIENT_ID: ${{ secrets.GATEWAY_CLIENT_ID }}
          GATEWAY_CLIENT_SECRET: ${{ secrets.GATEWAY_CLIENT_SECRET }}
          SESSIONS_DB_NAME: ${{ vars.SESSIONS_DB_NAME }}
          SESSIONS_DB_USER: ${{ secrets.SESSIONS_DB_USER }}
          SESSIONS_DB_PASS: ${{ secrets.SESSIONS_DB_PASS }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          KC_HOSTNAME: ${{ vars.KC_HOSTNAME }}
          KC_REALM_NAME: ${{ vars.KC_REALM_NAME }}
          IMAGE: ${{ env.IMAGE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GATEWAY_CLIENT_ID,GATEWAY_CLIENT_SECRET,SESSIONS_DB_NAME,SESSIONS_DB_USER,SESSIONS_DB_PASS,FRONTEND_URL,KC_HOSTNAME,KC_REALM_NAME,IMAGE
          script: |
            cd "${{ vars.SERVER_INFRA_PATH }}"
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker compose pull gateway
            docker compose up -d --no-deps gateway
            docker image prune -f
