name: Deploy Infrastructure (Postgres, Keycloak)

on: workflow_dispatch

permissions: {}

jobs:
  deploy-infra:
    name: Deploy infrastructure
    environment: production
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # 1. Очистка целевых папок инфраструктуры на сервере перед копированием файлов
      - name: Prepare Directory via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ${{ vars.SERVER_INFRA_PATH }}
            rm -rf ${{ vars.SERVER_INFRA_PATH }}/database
            rm -rf ${{ vars.SERVER_INFRA_PATH }}/iam

      # 2. Копируем конфигурации и папки со всеми вложенными файлами на VDS
      - name: Copy Config and Source Files to VDS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml,database/**,iam/**"
          target: "${{ vars.SERVER_INFRA_PATH }}"

      # 3. Пересобираем образы и запускаем контейнеры с передачей секретов
      - name: Build and Start Infrastructure via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |

            # Присваиваем значение в bash-переменную для удобства работы внутри скрипта
            cd "${{ vars.SERVER_INFRA_PATH }}"

            #sed -i 's/\r$//' database/init_db.sh 2>/dev/null || true

            # Секреты для БД
            echo "POSTGRES_USER=${{ secrets.ROOT_DB_USER }}" > .env
            echo "POSTGRES_PASS=${{ secrets.ROOT_DB_PASS }}" >> .env
            echo "IAM_DB_USER=${{ secrets.IAM_DB_USER }}" >> .env
            echo "IAM_DB_PASS=${{ secrets.IAM_DB_PASS }}" >> .env
            echo "IAM_DB_NAME=${{ vars.IAM_DB_NAME }}" >> .env
            echo "SESSIONS_DB_USER=${{ secrets.SESSIONS_DB_USER }}" >> .env
            echo "SESSIONS_DB_PASS=${{ secrets.SESSIONS_DB_PASS }}" >> .env
            echo "SESSIONS_DB_NAME=${{ vars.SESSIONS_DB_NAME }}" >> .env
            echo "BACKEND_DB_USER=${{ secrets.BACKEND_DB_USER }}" >> .env
            echo "BACKEND_DB_PASS=${{ secrets.BACKEND_DB_PASS }}" >> .env
            echo "BACKEND_DB_NAME=${{ vars.BACKEND_DB_NAME }}" >> .env
            
            # Секреты для Keycloak
            echo "KEYCLOAK_ADMIN_USER=${{ secrets.KEYCLOAK_ADMIN_USER }}" >> .env
            echo "KEYCLOAK_ADMIN_PASS=${{ secrets.KEYCLOAK_ADMIN_PASS }}" >> .env
            
            # Окружение хоста для работы за Nginx прокси
            echo "KC_HOSTNAME=${{ vars.KC_HOSTNAME }}" >> .env
            
            # Дополнительные переменные для шлюза (так как они теперь есть в docker-compose)
            echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
            echo "KC_REALM_NAME=${{ vars.KC_REALM_NAME }}" >> .env
            echo "GATEWAY_CLIENT_ID=${{ vars.GATEWAY_CLIENT_ID }}" >> .env
            echo "GATEWAY_CLIENT_SECRET=${{ secrets.GATEWAY_CLIENT_SECRET }}" >> .env
            
            # Жестко останавливаем старые контейнеры, если они зависли
            docker compose down --remove-orphans || true
            
            # Запускаем сборку заново
            docker compose --env-file .env up -d --build
