name: Deploy Jaeger Config

on:
  push:
    branches:
      - master
    paths:
      - 'jaeger/jaeger-ui.json'
      - '.github/workflows/deploy-jaeger-config.yml'
permissions: {}

jobs:
  deploy-config:
    name: Deploy Jaeger Config
    environment: production
    permissions:
      contents: read
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Copy jaeger-ui.json to VDS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "jaeger/jaeger-ui.json"
          target: "${{ vars.SERVER_PROJECT_PATH }}"
          strip_components: 1

      - name: Restart Jaeger container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{ vars.SERVER_PROJECT_PATH }}"
            docker compose up -d --force-recreate --no-deps jaeger
