name: Deploy Tasks-service

on:
  push:
    branches:
      - master
    paths:
      - 'tasks-service/**'
      - '.github/workflows/deploy-tasks-service.yml'
  workflow_run:
    workflows:
      - "Deploy Infrastructure (Postgres, Keycloak)"
    types:
      - completed
permissions: {}

jobs:
  deploy:
    name: Deploy tasks-service
    environment: production
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    env:
      RDBMS_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.RDBMS_IMAGE_NAME }}
      IAM_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IAM_IMAGE_NAME }}
      GATEWAY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.GATEWAY_IMAGE_NAME }}
      TASKS_SERVICE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TASKS_SERVICE_IMAGE_NAME }}
      IAM_ISSUER_URI: ${{ vars.KC_HOSTNAME }}/realms/${{ vars.KC_REALM_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./tasks-service
          push: true
          tags: ${{ env.TASKS_SERVICE_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy docker-compose.yml to VDS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "${{ vars.SERVER_PROJECT_PATH }}"

      - name: Deploy to VDS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "${{ vars.SERVER_PROJECT_PATH }}"

            export RDBMS_IMAGE="${{ env.RDBMS_IMAGE }}"
            export IAM_IMAGE="${{ env.IAM_IMAGE }}"
            export GATEWAY_IMAGE="${{ env.GATEWAY_IMAGE }}"
            export TASKS_SERVICE_IMAGE="${{ env.TASKS_SERVICE_IMAGE }}"

            export TASKS_SERVICE_DB_NAME="${{ vars.TASKS_SERVICE_DB_NAME }}"
            export TASKS_SERVICE_DB_USER="${{ secrets.TASKS_SERVICE_DB_USER }}"
            export TASKS_SERVICE_DB_PASS="${{ secrets.TASKS_SERVICE_DB_PASS }}"
            export IAM_ISSUER_URI="${{ env.IAM_ISSUER_URI }}"

            docker compose pull tasks-service
            docker compose up -d --no-deps tasks-service
            docker image prune -f





